# Generated by Django 5.0.7 on 2026-10-07 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0003_topic_keywords_topic_max_students_topic_requirements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='Tên mốc hoặc đợt báo cáo (vd: Tuần 3, Mốc 1)', max_length=100)),
                ('stage', models.CharField(blank=True, help_text='Giai đoạn thực hiện (vd: Báo cáo tổng quan, Thiết kế kiến trúc)', max_length=100)),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='Phần trăm hoàn thành (0-100%)')),
                ('content', models.TextField(help_text='Nội dung kết quả đã thực hiện')),
                ('attachment', models.FileField(blank=True, help_text='File tài liệu đính kèm (Word, PDF, ZIP... <= 20MB)', null=True, upload_to='progress_attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='Cờ tự động đánh dấu trễ tiến độ nếu nộp sau thời hạn/quy định')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='topics.topicassignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Nội dung nhận xét/gợi ý của Giảng viên')),
                ('score', models.FloatField(blank=True, help_text='Điểm đánh giá giai đoạn (nếu có, thang điểm 10)', null=True)),
                ('result', models.CharField(choices=[('passed', 'Đạt'), ('need_revision', 'Cần chỉnh sửa'), ('failed', 'Không đạt')], default='passed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='progress.progressreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
