# Generated by Django 5.0.7 on 2026-10-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, help_text='Tên lớp (nếu role=student)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.cohort'),
        ),
    ]
