# Generated by Django 5.0.7 on 2026-08-24 03:26

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('rename_requested', 'Yêu cầu sửa tên')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Ghi chú của Trưởng bộ môn khi duyệt/từ chối/yêu cầu sửa')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='academics.academicyear')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='academics.cohort')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='academics.department')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='academics.field')),
                ('proposed_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_topics', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topics', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='academics.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='assigned_topics', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='topics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tạo mới'), ('updated', 'Cập nhật'), ('approved', 'Duyệt'), ('rejected', 'Từ chối'), ('rename_requested', 'Yêu cầu sửa tên'), ('assigned', 'Giao đề tài')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='topics.topic')),
            ],
            options={
                'verbose_name_plural': 'Topic histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_percent', models.FloatField(help_text='0-100')),
                ('warning_level', models.CharField(choices=[('normal', 'Bình thường'), ('review', 'Cần xem xét'), ('high', 'Tương đồng cao'), ('duplicate', 'Có khả năng trùng đề tài')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similar_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topics.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_results', to='topics.topic')),
            ],
            options={
                'ordering': ['-similarity_percent'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status'], name='topics_topi_status_54d68a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['cohort', 'academic_year', 'semester'], name='topics_topi_cohort__9ee6f3_idx'),
        ),
    ]
