# Generated by Django 5.0.7 on 2026-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách từ khóa đề tài (dạng array chuỗi)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=1, help_text='Số lượng sinh viên tối đa được giao'),
        ),
        migrations.AddField(
            model_name='topic',
            name='requirements',
            field=models.TextField(blank=True, help_text='Yêu cầu thực hiện đề tài'),
        ),
        migrations.AddField(
            model_name='topicassignment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Thời hạn hoàn thành đồ án', null=True),
        ),
        migrations.AddField(
            model_name='topicassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='topichistory',
            name='action',
            field=models.CharField(choices=[('created', 'Tạo mới'), ('updated', 'Cập nhật'), ('resubmitted', 'Nộp lại'), ('approved', 'Duyệt'), ('rejected', 'Từ chối'), ('rename_requested', 'Yêu cầu sửa tên'), ('assigned', 'Giao đề tài')], max_length=20),
        ),
    ]
