# Generated by Django 5.0.7 on 2026-10-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_resources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsimilarityresult',
            options={'ordering': ['rank', '-similarity_percent']},
        ),
        migrations.AddField(
            model_name='topicsimilarityresult',
            name='assessment_status',
            field=models.CharField(choices=[('disabled', 'Chưa bật đánh giá bổ sung'), ('completed', 'Đã đánh giá bổ sung'), ('unavailable', 'Đánh giá bổ sung tạm thời không khả dụng'), ('exact_match', 'Trùng tên chính xác')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='topicsimilarityresult',
            name='groq_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topicsimilarityresult',
            name='groq_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsimilarityresult',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
